### ISSUE TITLE
Unable to download bigann-1B dataset

### ISSUE THREAD

**Issue by rajesh0346** [harsha-simhadri/big-ann-benchmarks#127] opened 2023-06-26 09:38 UTC
I am trying to get bigann-1B dataset using following command, But it fails with error.
Is there an alternative source for this dataset ??

(big-ann) ubuntu@ip-172-31-2-12:~/pgvector_testing/big-ann-benchmarks$ python create_dataset.py --dataset bigann-1B
downloading https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/bigann/query.public.10K.u8bin -> data/bigann/query.public.10K.u8bin...
  [0.24 s] downloaded 1.22 MiB / 1.22 MiB at 5.10 MiB/s
download finished in 0.24 s, total size 1280008 bytes
downloading https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/bigann/GT.public.1B.ibin -> data/bigann/GT.public.1B.ibin...
  [0.40 s] downloaded 7.63 MiB / 7.63 MiB at 19.18 MiB/s
download finished in 0.40 s, total size 8000008 bytes
downloading https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/bigann/query.private.799253207.10K.u8bin -> data/bigann/query.private.799253207.10K.u8bin...
Traceback (most recent call last):
  File "/home/ubuntu/pgvector_testing/big-ann-benchmarks/create_dataset.py", line 16, in <module>
    ds.prepare(True if args.skip_data else False)
  File "/home/ubuntu/pgvector_testing/big-ann-benchmarks/benchmark/datasets.py", line 140, in prepare
    download(self.private_qs_url, outfile)
  File "/home/ubuntu/pgvector_testing/big-ann-benchmarks/benchmark/dataset_io.py", line 25, in download
    inf = urlopen(src)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by harsha-simhadri** [comment] 2023-07-02 20:14
its now fixed

**Comment by s417-lama** [comment] 2023-10-21 11:11
I guess this issue still exists:

```
$ python3 create_dataset.py --dataset bigann-10M
downloading https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/bigann/query.public.10K.u8bin -> data/bigann/query.public.10K.u8bin...
  [1.10 s] downloaded 1.22 MiB / 1.22 MiB at 1.11 MiB/s
download finished in 1.10 s, total size 1280008 bytes
downloading https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/GT_10M/bigann-10M -> data/bigann/bigann-10M...
  [1.64 s] downloaded 7.63 MiB / 7.63 MiB at 4.66 MiB/s
download finished in 1.64 s, total size 8000008 bytes
downloading https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/bigann/query.private.799253207.10K.u8bin -> data/bigann/query.private.799253207.10K.u8bin...
Traceback (most recent call last):
  File "/home/USER/workspace/playground/big-ann-benchmarks/create_dataset.py", line 16, in <module>
    ds.prepare(True if args.skip_data else False)
  File "/home/USER/workspace/playground/big-ann-benchmarks/benchmark/datasets.py", line 140, in prepare
    download(self.private_qs_url, outfile)
  File "/home/USER/workspace/playground/big-ann-benchmarks/benchmark/dataset_io.py", line 25, in download
    inf = urlopen(src)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by maumueller** [comment] 2023-10-23 07:20
I can confirm this. Not sure if @harsha-simhadri or @mdouze own these files.

**Comment by harsha-simhadri** [comment] 2023-10-25 18:58
@mdouze  
owns the file https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/bigann/query.private.799253207.10K.u8bin -> data/bigann/query.private.799253207.10K.u8bin

**Comment by AM-ash-OR-AM-I** [comment] 2023-10-31 06:35
any updates on this issue? it still persists..

**Comment by mdouze** [comment] 2023-11-02 17:04
Those are the private queries, why do you need to access them?

**Comment by s417-lama** [comment] 2023-11-03 16:00
I don't need them, but lack of them causes the download command to fail.

**Comment by karim-manaouil** [comment] 2023-11-21 17:17
@maumueller the issue is still there. Is there any chance it could be fixed?

**Closed** 2023-11-22 13:29 UTC
